export const ADD_COMPANY = "ADD_COMPANY";
export const JOIN_COMPANY = "JOIN_COMPANY";
export const SEARCH_COMPANY = "SEARCH_COMPANY";
export const ERR_COMPANY = "ERR_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIES_BY_NAME = "GET_COMPANIES_BY_NAME";

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';