export const ADD_COMPANY = "ADD_COMPANY";
export const JOIN_COMPANY = "JOIN_COMPANY";
export const SEARCH_COMPANY = "SEARCH_COMPANY";
export const ERR_COMPANY = "ERR_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const GET_COMPANIES_BY_NAME = "GET_COMPANIES_BY_NAME";
export const GET_OWNED_COMPANIES = "GET_OWNED_COMPANIES";
export const GET_JOINED_COMPANIES = "GET_JOINED_COMPANIES";
export const CLEAR_SEARCH_COMPANIES = "CLEAR_SEARCH_COMPANIES";
export const GET_CURRENT_COMPANY = "GET_CURRENT_COMPANY";
export const GET_BANK = "GET_BANK";
export const GET_BANK_EMPLOYEES = "GET_BANK_EMPLOYEES";
export const GET_GRAPH_DATA = "GET_GRAPH_DATA";
export const GET_COMPANY_PROFILE = "GET_COMPANY_PROFILE";
export const CLEAR_COMPANY = "CLEAR_COMPANY";

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const GET_PROFILE = 'GET_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const COMPLETE_COURSE = "COMPLETE_COURSE";


export const ADD_COURSE = 'ADD_COURSE';
export const GET_COMPANY_COURSES = 'GET_COMPANY_COURSES';
export const ERR_COURSE = 'ERR_COURSE';

export const ADD_TASK = 'ADD_TASK';
export const GET_TASK = 'GET_TASK';
export const GET_COMPANY_TASKS = 'GET_COMPANY_TASKS';
export const ERR_TASK = 'ERR_TASK';
